# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKxpe-0KuYdIUO7ZjSJZ-fwQwee6OuL4
"""

# We are bringing in the tools we need for our analysis

import pandas as pd               # pandas helps us load and work with our data like a spreadsheet
import matplotlib.pyplot as plt   # matplotlib is what draws our charts
import seaborn as sns             # seaborn makes our charts look clean and professional
import warnings                   # this helps us hide unnecessary warning messages
warnings.filterwarnings('ignore') # turn off warnings so our output stays clean

# This sets a clean white background for all our charts
sns.set_theme(style="whitegrid")

# This sets the default size of every chart we draw
plt.rcParams['figure.figsize'] = (10, 5)

print("All libraries loaded successfully!")

# We are loading our CSV file into a dataframe called df
# A dataframe is like an Excel spreadsheet inside Python
# Make sure you have uploaded bank-full.csv to your Colab session first

df = pd.read_csv('bank-full.csv', sep=';')
# sep=';' tells Python that the columns in this file are separated by semicolons

print("Dataset loaded successfully!")
print(f"Rows: {df.shape[0]}")      # how many customers are in the dataset
print(f"Columns: {df.shape[1]}")   # how many pieces of information we have per customer

# Let's look at the first 5 rows to understand what our data looks like
df.head()

# This checks if any column has missing values
# A 0 means no missing values which is good
print("Missing Values Per Column:")
print(df.isnull().sum())

# Let's first understand how many people said yes vs no overall
# This is our target column called y

# Count how many yes and no responses we have
subscription_counts = df['y'].value_counts()

# Calculate the percentage of each
subscription_percent = df['y'].value_counts(normalize=True) * 100

print("Subscription Counts:")
print(subscription_counts)
print("\nSubscription Percentage:")
print(subscription_percent.round(1))

# Let's count how many customers said yes and how many said no
# value_counts() counts each unique value in the y column

subscription_counts = df['y'].value_counts()
# normalize=True converts the counts into percentages
subscription_percent = df['y'].value_counts(normalize=True) * 100

print("Subscription Counts:")
print(subscription_counts)
print("\nSubscription Percentage:")
print(subscription_percent.round(1))

# Now let us visualize the yes vs no split as a pie chart and a bar chart side by side

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
# fig is our canvas, axes are the two chart areas
# 1, 2 means 1 row and 2 columns — so two charts side by side

# ── Left Chart: Pie Chart ──
axes[0].pie(
    subscription_counts,                        # the values to plot
    labels=['Did Not Subscribe', 'Subscribed'], # labels for each slice
    colors=['#E74C3C', '#2ECC71'],              # red for no, green for yes
    autopct='%1.1f%%',                          # show percentage on each slice
    startangle=90,                              # start the pie from the top
    textprops={'fontsize': 11}
)
axes[0].set_title('Overall Subscription Split', fontsize=13, fontweight='bold', color='#1F4E79')

# ── Right Chart: Bar Chart ──
bars = axes[1].bar(
    ['Did Not Subscribe', 'Subscribed'],        # labels on x axis
    subscription_counts.values,                 # the count values
    color=['#E74C3C', '#2ECC71'],               # red for no, green for yes
    edgecolor='white',                          # white border on each bar
    width=0.5                                   # width of each bar
)

# Add the number on top of each bar so it is easy to read
for bar in bars:
    height = bar.get_height()                   # get the height of each bar
    axes[1].text(
        bar.get_x() + bar.get_width() / 2,     # position in the middle of the bar
        height + 200,                           # just above the bar
        f'{int(height):,}',                    # the count formatted with comma
        ha='center', fontsize=11, fontweight='bold', color='#1F4E79'
    )

axes[1].set_title('Subscription Count', fontsize=13, fontweight='bold', color='#1F4E79')
axes[1].set_ylabel('Number of Customers', fontsize=11)
axes[1].grid(axis='y', alpha=0.4)              # light horizontal grid lines

plt.suptitle('How Many Customers Subscribed?', fontsize=15, fontweight='bold', color='#1F4E79', y=1.02)
plt.tight_layout()                              # makes sure charts do not overlap
plt.savefig('overall_subscription.png', dpi=150, bbox_inches='tight') # saves the chart
plt.show()

print("\n📊 FINDING: Only 11.7% of customers subscribed. This means the bank contacted many people who were unlikely to say yes.")

"""That means out of 45,211 customers contacted, only 5,289 subscribed.

"""

# We want to know which job types have the highest subscription rate
# First we calculate the subscription rate per job group

job_rate = (
    df.groupby('job')['y']              # group the data by job type
    .apply(lambda x: (x == 'yes').mean() * 100)  # calculate % who said yes
    .reset_index()                       # turn the result into a clean table
    .rename(columns={'y': 'subscription_rate'})   # rename the column
    .sort_values('subscription_rate', ascending=False)  # sort highest to lowest
)

print(job_rate.round(1))               # print the table so we can see the numbers

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# ── Left Chart: Bar chart of subscription rate by job ──
bars = axes[0].bar(
    job_rate['job'],                    # job types on x axis
    job_rate['subscription_rate'],      # subscription rate on y axis
    color='#3498DB',                    # blue bars
    edgecolor='white',
    width=0.6
)

# Add percentage label on top of each bar
for bar in bars:
    height = bar.get_height()
    axes[0].text(
        bar.get_x() + bar.get_width() / 2,
        height + 0.3,
        f'{height:.1f}%',
        ha='center', fontsize=8, fontweight='bold', color='#1F4E79'
    )

# Add a red dashed line showing the overall average
overall_avg = (df['y'] == 'yes').mean() * 100
axes[0].axhline(
    y=overall_avg,                      # draw a line at the overall average
    color='#E74C3C',
    linestyle='--',
    linewidth=1.5,
    label=f'Overall Average: {overall_avg:.1f}%'
)

axes[0].set_title('Subscription Rate by Job Type', fontsize=13, fontweight='bold', color='#1F4E79')
axes[0].set_xlabel('Job Type', fontsize=11)
axes[0].set_ylabel('Subscription Rate (%)', fontsize=11)
axes[0].tick_params(axis='x', rotation=45) # rotate job labels so they fit
axes[0].legend(fontsize=9)
axes[0].grid(axis='y', alpha=0.4)

# ── Right Chart: Histogram of age by subscription outcome ──
# A histogram shows us the distribution — where most customers fall by age

sns.histplot(
    data=df,                            # our full dataset
    x='age',                            # age on the x axis
    hue='y',                            # colour by yes or no
    bins=20,                            # split age into 20 groups
    palette={'yes': '#2ECC71', 'no': '#E74C3C'},  # green for yes, red for no
    alpha=0.7,                          # slight transparency so bars overlap nicely
    ax=axes[1]                          # draw this in the right chart area
)

axes[1].set_title('Age Distribution by Subscription Outcome', fontsize=13, fontweight='bold', color='#1F4E79')
axes[1].set_xlabel('Age', fontsize=11)
axes[1].set_ylabel('Number of Customers', fontsize=11)
axes[1].grid(axis='y', alpha=0.4)

plt.suptitle('Business Question 1: Who Subscribes by Job and Age?', fontsize=14, fontweight='bold', color='#1F4E79', y=1.02)
plt.tight_layout()
plt.savefig('Q1_job_and_age.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n📊 FINDING: Students and retired customers subscribe at the highest rates.")
print("   Blue-collar and service workers are the least likely to subscribe.")

# We want to know if calling a customer more times helps or hurts

# Calculate subscription rate by number of contacts
# We limit to 10 contacts because beyond that the numbers are very small
df_camp = df[df['campaign'] <= 10]     # filter to customers contacted 10 times or fewer

camp_rate = (
    df_camp.groupby('campaign')['y']
    .apply(lambda x: (x == 'yes').mean() * 100)
    .reset_index()
    .rename(columns={'y': 'subscription_rate'})
)

print(camp_rate.round(1))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# ── Left Chart: Bar chart — contacts vs subscription rate ──
bars = axes[0].bar(
    camp_rate['campaign'],
    camp_rate['subscription_rate'],
    color='#9B59B6',                    # purple bars
    edgecolor='white',
    width=0.6
)

for bar in bars:
    height = bar.get_height()
    axes[0].text(
        bar.get_x() + bar.get_width() / 2,
        height + 0.3,
        f'{height:.1f}%',
        ha='center', fontsize=8, fontweight='bold', color='#4A235A'
    )

axes[0].axhline(y=overall_avg, color='#E74C3C', linestyle='--',
                linewidth=1.5, label=f'Overall Average: {overall_avg:.1f}%')
axes[0].set_title('Subscription Rate by Number of Contacts', fontsize=13, fontweight='bold', color='#1F4E79')
axes[0].set_xlabel('Number of Times Customer Was Contacted', fontsize=11)
axes[0].set_ylabel('Subscription Rate (%)', fontsize=11)
axes[0].legend(fontsize=9)
axes[0].grid(axis='y', alpha=0.4)

# ── Right Chart: Histogram — how many times were customers contacted? ──
sns.histplot(
    data=df_camp,
    x='campaign',
    hue='y',
    bins=10,
    palette={'yes': '#2ECC71', 'no': '#E74C3C'},
    alpha=0.7,
    ax=axes[1]
)

axes[1].set_title('Contact Frequency: Subscribed vs Not Subscribed', fontsize=13, fontweight='bold', color='#1F4E79')
axes[1].set_xlabel('Number of Contacts', fontsize=11)
axes[1].set_ylabel('Number of Customers', fontsize=11)
axes[1].grid(axis='y', alpha=0.4)

plt.suptitle('Business Question 2: Does Calling More Times Help?', fontsize=14, fontweight='bold', color='#1F4E79', y=1.02)
plt.tight_layout()
plt.savefig('Q2_campaign_contacts.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n📊 FINDING: The first contact has the highest subscription rate.")
print("   Calling customers more than 3 times rarely leads to a subscription.")

# We want to know if longer calls lead to more subscriptions

# Calculate average and median call duration by outcome
duration_stats = df.groupby('y')['duration'].agg(['mean', 'median']).round(0)
print("Call Duration Statistics by Outcome:")
print(duration_stats)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# ── Left Chart: Box plot — duration by subscription outcome ──
# A box plot shows us the spread of the data — minimum, median, and maximum
df_dur = df[df['duration'] <= 2000]    # remove extreme outliers above 2000 seconds

sns.boxplot(
    data=df_dur,
    x='y',
    y='duration',
    palette={'yes': '#2ECC71', 'no': '#E74C3C'},
    width=0.4,
    ax=axes[0]
)

# Add median label on each box
for i, outcome in enumerate(['no', 'yes']):
    med = df_dur[df_dur['y'] == outcome]['duration'].median()
    axes[0].text(i, med + 20, f'Median: {med:.0f}s',
                 ha='center', fontsize=10, fontweight='bold', color='#1F4E79')

axes[0].set_title('Call Duration by Subscription Outcome', fontsize=13, fontweight='bold', color='#1F4E79')
axes[0].set_xlabel('Subscribed', fontsize=11)
axes[0].set_ylabel('Call Duration (seconds)', fontsize=11)
axes[0].grid(axis='y', alpha=0.4)

# ── Right Chart: Histogram — call duration distribution ──
sns.histplot(
    data=df_dur,
    x='duration',
    hue='y',
    bins=30,
    palette={'yes': '#2ECC71', 'no': '#E74C3C'},
    alpha=0.7,
    ax=axes[1]
)

# Add vertical median lines so it is easy to see the difference
med_yes = df[df['y'] == 'yes']['duration'].median()
med_no  = df[df['y'] == 'no']['duration'].median()

axes[1].axvline(med_yes, color='#1B5E20', linestyle='--', linewidth=2, label=f'Median Yes: {med_yes:.0f}s')
axes[1].axvline(med_no,  color='#B71C1C', linestyle='--', linewidth=2, label=f'Median No: {med_no:.0f}s')
axes[1].legend(fontsize=9)
axes[1].set_title('Call Duration Distribution: Yes vs No', fontsize=13, fontweight='bold', color='#1F4E79')
axes[1].set_xlabel('Call Duration (seconds)', fontsize=11)
axes[1].set_ylabel('Number of Customers', fontsize=11)
axes[1].grid(axis='y', alpha=0.4)

plt.suptitle('Business Question 3: Do Longer Calls Lead to Subscriptions?', fontsize=14, fontweight='bold', color='#1F4E79', y=1.02)
plt.tight_layout()
plt.savefig('Q3_call_duration.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n📊 FINDING: Customers who subscribed had much longer calls on average.")
print("   This suggests that keeping a customer engaged on the call increases the chance they say yes.")

# We want to know which months of the year had the highest subscription rates

month_order = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']

# Make month a category with the correct order so charts show Jan to Dec
df['month'] = pd.Categorical(df['month'], categories=month_order, ordered=True)

month_rate = (
    df.groupby('month', observed=True)['y']
    .apply(lambda x: (x == 'yes').mean() * 100)
    .reset_index()
    .rename(columns={'y': 'subscription_rate'})
)

print(month_rate.round(1))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# ── Left Chart: Bar chart — subscription rate by month ──
# Colour bars above average darker so they stand out
colors = ['#1F4E79' if v >= overall_avg else '#90CAF9'
          for v in month_rate['subscription_rate']]

bars = axes[0].bar(
    month_rate['month'],
    month_rate['subscription_rate'],
    color=colors,
    edgecolor='white',
    width=0.6
)

for bar in bars:
    height = bar.get_height()
    axes[0].text(
        bar.get_x() + bar.get_width() / 2,
        height + 0.3,
        f'{height:.1f}%',
        ha='center', fontsize=8, fontweight='bold', color='#1F4E79'
    )

axes[0].axhline(y=overall_avg, color='#E74C3C', linestyle='--',
                linewidth=1.5, label=f'Overall Average: {overall_avg:.1f}%')
axes[0].set_title('Subscription Rate by Month\n(Dark Blue = Above Average)', fontsize=12, fontweight='bold', color='#1F4E79')
axes[0].set_xlabel('Month', fontsize=11)
axes[0].set_ylabel('Subscription Rate (%)', fontsize=11)
axes[0].legend(fontsize=9)
axes[0].grid(axis='y', alpha=0.4)

# ── Right Chart: Histogram — how many calls were made each month ──
month_counts = df.groupby('month', observed=True).size().reset_index(name='count')

axes[1].bar(
    month_counts['month'],
    month_counts['count'],
    color='#F39C12',                    # orange bars for call volume
    edgecolor='white',
    width=0.6
)

for i, row in month_counts.iterrows():
    axes[1].text(i, row['count'] + 100, f"{row['count']:,}",
                 ha='center', fontsize=7, fontweight='bold', color='#784212')

axes[1].set_title('Total Calls Made by Month', fontsize=13, fontweight='bold', color='#1F4E79')
axes[1].set_xlabel('Month', fontsize=11)
axes[1].set_ylabel('Number of Calls', fontsize=11)
axes[1].grid(axis='y', alpha=0.4)

plt.suptitle('Business Question 4: Which Months Work Best?', fontsize=14, fontweight='bold', color='#1F4E79', y=1.02)
plt.tight_layout()
plt.savefig('Q4_monthly_patterns.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n📊 FINDING: March, September, October, and December have the highest subscription rates.")
print("   May has the most calls but one of the lower conversion rates — the bank is over-calling in May.")

# We want to know if customers who responded positively before are more likely to subscribe again

pout_rate = (
    df.groupby('poutcome')['y']
    .apply(lambda x: (x == 'yes').mean() * 100)
    .reset_index()
    .rename(columns={'y': 'subscription_rate'})
    .sort_values('subscription_rate', ascending=False)
)

print("Subscription Rate by Previous Campaign Outcome:")
print(pout_rate.round(1))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# ── Left Chart: Bar chart — subscription rate by previous outcome ──
bar_colors = {'success': '#2ECC71', 'failure': '#E74C3C',
              'other': '#F39C12', 'unknown': '#95A5A6'}
colors = [bar_colors.get(p, '#95A5A6') for p in pout_rate['poutcome']]

bars = axes[0].bar(
    pout_rate['poutcome'],
    pout_rate['subscription_rate'],
    color=colors,
    edgecolor='white',
    width=0.5
)

for bar in bars:
    height = bar.get_height()
    axes[0].text(
        bar.get_x() + bar.get_width() / 2,
        height + 0.5,
        f'{height:.1f}%',
        ha='center', fontsize=11, fontweight='bold', color='#1F4E79'
    )

axes[0].axhline(y=overall_avg, color='#2C3E50', linestyle='--',
                linewidth=1.5, label=f'Overall Average: {overall_avg:.1f}%')
axes[0].set_title('Subscription Rate by Previous Campaign Outcome', fontsize=12, fontweight='bold', color='#1F4E79')
axes[0].set_xlabel('Previous Campaign Outcome', fontsize=11)
axes[0].set_ylabel('Subscription Rate (%)', fontsize=11)
axes[0].legend(fontsize=9)
axes[0].grid(axis='y', alpha=0.4)

# ── Right Chart: Histogram — how many customers fall in each previous outcome group ──
sns.histplot(
    data=df,
    x='poutcome',                       # previous outcome on x axis
    hue='y',                            # colour by current subscription outcome
    multiple='dodge',                   # place bars next to each other not stacked
    palette={'yes': '#2ECC71', 'no': '#E74C3C'},
    alpha=0.8,
    ax=axes[1]
)

axes[1].set_title('Previous Outcome: Who Subscribed This Time?', fontsize=12, fontweight='bold', color='#1F4E79')
axes[1].set_xlabel('Previous Campaign Outcome', fontsize=11)
axes[1].set_ylabel('Number of Customers', fontsize=11)
axes[1].grid(axis='y', alpha=0.4)

plt.suptitle('Business Question 5: Does Past Campaign History Matter?', fontsize=14, fontweight='bold', color='#1F4E79', y=1.02)
plt.tight_layout()
plt.savefig('Q5_previous_campaign.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n📊 FINDING: Customers who said yes in a previous campaign subscribe at 64.7% — nearly 6 times the overall rate.")
print("   The bank should prioritise re-contacting customers who previously subscribed.")

# Print a clean summary of all key findings

print("=" * 55)
print("   BANK MARKETING CAMPAIGN — KEY FINDINGS SUMMARY")
print("=" * 55)
print(f"\n Overall subscription rate          : {overall_avg:.1f}%")
print(f"\n Q1 — Highest subscribing job       : Student and Retired")
print(f"\n Q2 — Best number of contacts       : 1 contact")
print(f"\n Q3 — Median call (subscribed)      : {df[df['y']=='yes']['duration'].median():.0f} seconds")
print(f"      Median call (not subscribed)  : {df[df['y']=='no']['duration'].median():.0f} seconds")
print(f"\n Q4 — Best performing months        : Mar, Sep, Oct, Dec")
print(f"\n Q5 — Previous success rate         : {df[df['poutcome']=='success']['y'].apply(lambda x: 1 if x=='yes' else 0).mean()*100:.1f}%")
print("\n" + "=" * 55)

